#!/usr/bin/env bash

# https://github.com/cmhughes/latexindent.pl/blob/main/Dockerfile

set -xueo pipefail

docker pull ghcr.io/cmhughes/latexindent.pl 1>&2

CONFIG="${HOME}/dotfiles/local/opt/latexindent/config.yaml"

docker run 							\
	--rm 							\
	-i 							\
	--name "latexindent"					\
	-v "${CONFIG}":/io/config.yaml				\
	ghcr.io/cmhughes/latexindent.pl 			\
	-m -l "/io/config.yaml" -
