#!/usr/bin/env bash

# https://github.com/cmhughes/latexindent.pl/blob/main/Dockerfile

set -xueo pipefail

docker pull ghcr.io/cmhughes/latexindent.pl 1>&2

#DEFAULT_FLAGS="-s -w"

docker run 							\
	--rm 							\
	-i 							\
	--name "latexindent"					\
	ghcr.io/cmhughes/latexindent.pl 			\
	${DEFAULT_FLAGS:-} ${FLAGS:-}
