FROM docker.io/debian:bullseye

RUN set -e 							&& \
    apt-get update 						&& \
    apt-get upgrade -yq 					&& \
    apt-get install -yq --no-install-recommends			\
    	apt-utils						\
	build-essential						\
	ca-certificates						\
	curl							\
	elfutils						\
	gcc							\
	gcc-multilib						\
	gdb-multiarch						\
	gdbserver						\
	git							\
	glibc-source						\
	jq							\
	libc6-dev						\
	libc6-dbg						\
	libgmp-dev						\
	llvm							\
	ltrace							\
	nasm							\
	python3							\
	python3-dev						\
	python3-pip						\
	ripgrep							\
	sudo							\
	strace							\
	texinfo							\
	tmux							\
	tree							\
	vim							\
	wget							\
	z3							\
	zsh							&& \
    apt-mark hold libc6						&& \
    apt-mark hold libc-bin					&& \
    python3 -m pip install --upgrade --no-cache-dir pip 	&& \
    apt-get -y autoremove --purge 				&& \
    apt-get clean 						&& \
    rm -rf /var/lib/apt/lists/*

WORKDIR /opt/gef
RUN set -e 							&& \
    curl -fsSL https://gef.blah.cat/py				\
        --output /opt/gef/gdbinit-gef.py			&& \
    echo "source ~/.gdbinit_local" > ~/.gdbinit			&& \
    echo "#source /opt/gef/gdbinit-gef.py" >> ~/.gdbinit

WORKDIR /opt
RUN set -e 							&& \
    git clone https://github.com/pwndbg/pwndbg			&& \
    cd /opt/pwndbg						&& \
    ./setup.sh

RUN set -e 							&& \
    pip install							\
        pwntools						\
	keystone-engine						\
	ropper							\
	z3-solver						\
	git+https://github.com/martinclauss/syscall_number.git

WORKDIR /io
